### ISSUE TITLE
don't release on chore commits

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#128]
We shouldn't be making releases when we have only chore commits as noting should have changed for the user in those commits, making the release unnecessary. Maybe we could move to [**`semantic-release`**](https://github.com/semantic-release/semantic-release), which also has some other benefits?

**Comment by wagoid** [comment]
Agreed! When I introduced automatic deployment I thought about `semantic-release`, but decided to go with `standard-version` directly as this direct usage was already enough for what I wanted. But I'm definitely happy using `semantic-release` too 🚀

**Comment by wagoid** [comment]
Just one detail, if we don't deploy on `chore` we'll need to update dependabot to use `chore` scope only for `devDependencies`, because updates to our `dependencies` need a new version of the action. That is, any features and fixes to deps such as `@commitlint/config-conventional` should be propagated to the action users 👍 
I believe the `prefix` and `prefix-development` on the [commit-message](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#commit-message) config of dependabot would work?
