### ISSUE TITLE
Getting unexplained errors after merging from feature branches

### ISSUE THREAD

**Issue by ashblue** [wagoid/commitlint-github-action#130]
I ran the suite fine in a feature branch and everything passed. Oddly things are suddenly failing after I merge them in. Maybe I'm just confused but I feel like this should be working fine. I tried the parent merge flag but it's still failing.

Working PR: https://github.com/ashblue/upm-package-populator/actions/runs/716021916
Fail after merge: https://github.com/ashblue/upm-package-populator/actions/runs/716024505

**Comment by wagoid** [comment]
Hi @ashblue! On your [checkout step](https://github.com/ashblue/upm-package-populator/blob/5c70cd131a0615872bbd81898e4e3ec5ad251f1c/.github/workflows/workflow.yml#L7), you need to specify a `fetch-dept` of `0` so that the action dowloads all commits when checking out. You can see more info about this requirement [here](https://github.com/wagoid/commitlint-github-action#usage).

Let me know if the problem still happens after adding this param!

**Comment by ashblue** [comment]
Ah okay that makes sense. I assumed that was a default value printed for debugging purposes. Surprised that isn't a default value built in, but I don't know much about Git Action programming yet. I'll give that a spin tonight and see if it fixes things.

**Comment by ashblue** [comment]
Yep I was just using the syntax wrong. All is good. 😅

**Comment by wagoid** [comment]
Nice, good to know it works now 🚀
