### ISSUE TITLE
Push action invalid revision

### ISSUE THREAD

**Issue by vidavidorra** [wagoid/commitlint-github-action#18]
I'm using v1.3.0 and this error was from the second commit, in which no valid revision could be found.
See the log [here](https://github.com/vidavidorra/next-standard-version/commit/df3eddc3db5965e0fc8d2083486454f1fd3a3412/checks?check_suite_id=330897727#step:4:9). Looks to me like the `^1` after the fist hash is not valid in the case of there only being 2 commits. I haven't looked ad the code but why would you need to get the previous commit from the last known commit before the push?

The first commit worked correctly, but it detected an invalid commit message due to that commit being generated by GitHub and not valid style.

**Comment by wagoid** [comment]
Hi @vidavidorra, thank you for submitting this issue! This is done due to how git revision ranges work. When doing a `git log` for `SHA1..SHA2` the commit messages of `SHA1` will not be included. I didn't find a way to do this in one command without `^1` and ended up going with this quickest approach. I was aware it would break in this case but thought it would be too much of an edge case (i.e. only first push of a repo) so I didn't worry about it 🙈

Do you know of a solution in `git log` for this? Otherwise I will solve it by running two `git` commands :rocket:

**Comment by vidavidorra** [comment]
Are you using the `from` and `to` fields from commitlint to pass on the commit range it needs to run on? If so I think it should be okay to pass the `from` field as the last known commit hash before the push (`github.event.before`) and the `to` field with the current hash. Only on the first commit of the repo, I'm not sure what the `github.event.before` would be in that case, but that commit might not work and need some other way to pass the commit or commit message to commitlint.

**Comment by wagoid** [comment]
Yes, that's what I currently use as the `from` field for `push` events. For `pull_request` it's different, I need to get the first commit of the PR in that case.
The thing with `github.event.before` is that when I tested I got a behavior of github giving me the "oldest commit of the push", not "the commit before the push". I just re-checked this and `before` was showing correct information, so I guess at the time I misinterpreted the info.
Will remove `^1` from `push` events and keep the usage of `^1` only for PR events.
