### ISSUE TITLE
Confusion on use

### ISSUE THREAD

**Issue by rpopp-fni-stl-com** [wagoid/commitlint-github-action#188]
Hello, I'm a bit new to actions, so excuse me if my issue is of my own doing. 

I set up the commitlint action as documented (with one exception, I also perform the action on push) and as expected, on a commit without the correct styling, it fails... but, I _only_ see the failure under the actions tab for the repo.  I also see that the push succeeded.  Shouldn't commitlint fail (or kick back) the push and not allow it to proceed until the commitlint check has passed?  That is, shouldn't I see that happen at the time I attempt to push?

Thanks in advance

**Comment by wagoid** [comment]
Hey @rpopp-fni-stl-com! Github actions run only after the event was pushed to github, so this behavior is expected. Github has support for what they call [pre-receive hooks](https://docs.github.com/en/enterprise-server@3.0/admin/policies/enforcing-policy-with-pre-receive-hooks/creating-a-pre-receive-hook-script) but only on enterprise.

So there are a options to make sure commits are correctly validated before going to the main branch. I'd suggest using both of them:
1. Add [branch protection rules](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) to your repo. With branch protection rules, you can block direct commits to your main branch from being pushed without checks. When creating the protection rule, you can mark the checkbox `Require status checks to pass before merging`. After marking the checkbox, you can search for the name of the job that you want to require (e.g. `commitlint` if you used the same job name as we suggest on readme).
2. Add `commit-msg` or `pre-push` hooks using a tool such as [husky](https://github.com/typicode/husky). In my repo we run commitlint during `commit-msg` hook, you can see how we have this setup on [this PR](https://github.com/wagoid/commitlint-github-action/pull/101). Make sure you add `@commitlint/cli` as a dev dependency to your repo when doing this setup 👍 

First option is the one that actually blocks anyone from pushing "bad commits" to the main branch, and the second adds another check locally for increased developer experience.
Bear in mind option 2 doesn't guarantee bad commits will be blocked, because people can pass the `--no-verify` param to git when making a commit.

Let me know if anything on this explanation didn't make sense 💪

**Comment by wagoid** [comment]
@rpopp-fni-stl-com I'll close the issue, but feel free to message me again if you have any issues 👍
