### ISSUE TITLE
Errors on force-pushed PRs

### ISSUE THREAD

**Issue by alerque** [wagoid/commitlint-github-action#21]
I started setting up this Action [for one of my repos](https://github.com/sile-typesetter/sile/pull/752/files) and it looked like it worked the first time. I had deliberately entered an invalid commit message just to see if it caught the mistake, and it did.

I then fixed the commit and force-pushed the PR again. At that point [the action failed](https://github.com/sile-typesetter/sile/pull/752/checks?check_run_id=372581694#step:4:1) with some messages about not being able to find the commmit:

> fatal: ambiguous argument 'a82656b832bb511c587d1c7a29be42ef042017c9^1..a82656b832bb511c587d1c7a29be42ef042017c9': unknown revision or path not in the working tree.

Am I doing something wrong? Is this only because it's a commit with the Action config or will this be a problem with other PRs too?

**Comment by alerque** [comment]
Note the [action is working](https://github.com/alerque/sile/runs/372623348#step:4:1) on my fork on the push action, it's only failing on the PR I have open on that branch.

**Comment by wagoid** [comment]
hi @alerque, that's probably due to an update in `actions/checkout`. I got a similar issue in another project but didn't update readme here yet. In `checkout@v2` their clone logic only fetches the latest commit of the branch. Since we check multiple commit messages, we need to fetch more commits. If you add `fetch-dept: 0` parameter that will work (since it will fetch all commits):
```yaml
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
```

About the second action that you sent, the reason why it worked is because of 2 things: it was ran in a `push` event and commit was force-pushed. When commit is force-pushed I only check the latest commit of the push, because the `before` field from event's payload may not exist in history.

Let me know if the above fix works for you :rocket:

**Comment by alerque** [comment]
Thank you for the feedback @wagoid (and for this great little action!). That does seem to have resolved the issue for me. It would probably be useful to mention that in the docs and others are bound to run into this unexpectedly.

Feel free to close this issue because the problem is resolved or keep as a reminder until the documentation catches up.

**Comment by wagoid** [comment]
Awesome, I'm glad it worked out @alerque! Gonna update readme now :rocket:
