### ISSUE TITLE
How should the commit message "Merge branch 'main' into main" be handled?

### ISSUE THREAD

**Issue by AndysonDK** [wagoid/commitlint-github-action#275]
Take a loot at the merge commits at the bottom of this [PR](https://github.com/AndysonDK/syncbase/pull/1). The commitlint action reports these as errors. How should such commits be handled, is there some preferred/best practice way?

**Comment by jdbruijn** [comment]
I think the commit messages like "Merge" and "Revert" are actually ignored, as they should. Please have a closer look at you'r action errors. The first failure on the `Merge remote-tracking branch 'upstream/main' into main` commit is actually on the lint workflow and all later commits look to fail because of the `lol` commit message of commit https://github.com/AndysonDK/syncbase/pull/1/commits/226bbfdfec5ace888bfce515fcf7d75fedcff68a (for a PR we check all commits in the PR). Please reopen if that was not the issue, but from my quick analysis looks like it is.

**Comment by AndysonDK** [comment]
You're right!
