### ISSUE TITLE
Feature: make docker registry configurable.

### ISSUE THREAD

**Issue by Arphylion** [wagoid/commitlint-github-action#276]
The .github/workflows/ci.yml currently uses the docker hub registry hard-coded.
With a large enough GitHub Runner setup we run into pull rate limits.
We can solve that issue working with a proxy that caches it, however that requires a bit more configuration to the project.
A suggestion would be to do this using a registry secret the end user can provide.

**Comment by wagoid** [comment]
Hey @Arphylion! That's true, we should support this scenario. From an initial check it doesn't seem to be possible to provide a secret on the [runs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions) section. I've checked these alternatives so far:
- Github Packages: no pull rate limits but there's a 500MB Storage so I would need to delete old images.
- Run in nodejs runtime: need to double check if there's `git` in there
- Build the action every time: build will take some seconds without caching
- Use [composite actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions) to manually pull the action in one of the steps

At first I'm leaning towards the last alternative since it gives us full control while still leveraging docker. But I need to investigate deeper to be sure.

If you have thoughts or other alternatives in mind let me know 👍

**Comment by Arphylion** [comment]
We ended up solving the issue using a proxy that caches docker pulls in our infra.
Changing the registry should actually not have been a request I realize.

I'll close this, thanks for the response!
