### ISSUE TITLE
Weird commit range issues

### ISSUE THREAD

**Issue by Qix-** [wagoid/commitlint-github-action#340]
Getting very cryptic commit range issues in CI that don't happen locally. Not really sure what to do about it but commitlint is broken entirely on this repository. Could you perhaps help me debug this issue?

https://github.com/Qix-/node-editor/runs/5166007565?check_suite_focus=true

**Comment by wagoid** [comment]
Hey @Qix-! This happens because your `actions/checkout@v2` step is missing the `fetch-depth` param. This param is necessary because by default the checkout action only fetches one commit, which prevents commitlint from checking ranges of commit messages.

If you update your checkout step to this, it should do the trick:
```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

Later I'll add a handler for this error mentioning the `fetch-depth` param.

**Comment by Qix-** [comment]
Aha! Thank you for the response :)

**Comment by Qix-** [comment]
Worked great, thank you again :)
