### ISSUE TITLE
Any way to run on all commits since latest release?

### ISSUE THREAD

**Issue by evanstoddard23** [wagoid/commitlint-github-action#47]
I'd like to run commitlint on pushes to master in a workflow that includes semantic-release. Semantic-release ignores commits that don't follow convention, but I'd rather fail instead. I have commitlint running first in the workflow, but it only checks the commits that are a part of the push. Is there an option to specify a range of commits (I already have the number of commits since the latest tag).

**Comment by wagoid** [comment]
Hi @evanstoddard23! Ideally it would be good to prevent any commit from hitting master altogether when the commits don't follow the convention. You can add branch protection rules to the master branch, and allow a PR to be merged only if the commitlint check passes. When adding branch protection rules, also make sure you allow admins to bypass the protection and pass an admin's personal access token to semantic-release through `GH_TOKEN` or `GITHUB_TOKEN` env var.

If this option is not suited for you, I think it would be better that you run commitlint manually in your workflow instead of this action, so that you can do it in your specific scenario. The cli supports the `--from` and `--to` arguments, so you can pass the range that you have to these options, e.g.: `npx commitlint --from v1.0.0 --to v1.1.0`

Would any of these options work for you?

**Comment by evanstoddard23** [comment]
Hey @wagoid! I agree it's best to prevent those commits hitting master. I'm in the process of getting my org used to conventional commits/semantic release. During the adjustment, I figured I could turn on semantic release iff all commits to master since the last release follow convention. I will try accomplishing this with the CLI. Thanks for the tip and speedy response!

**Comment by wagoid** [comment]
@evanstoddard23 got it! Sounds like a plan 🚀
