### ISSUE TITLE
Add action to local workflow using pre-commit

### ISSUE THREAD

**Issue by medmouine-beneva** [wagoid/commitlint-github-action#526]
Hi, is there anyway to setup the same rules for a local development environment as pre-commit? The main goal is to ensure the check passes before submitting it to the workflow. 

Thanks!

**Comment by wagoid** [comment]
Hi @medmouine-beneva! For that you can install commitlint CLI and use a pre-commit tool such as husky for example. In the [getting started of commitlint](https://github.com/conventional-changelog/commitlint#getting-started) they explain how to do it. Let me know if that doesn't work 💪

**Comment by wagoid** [comment]
@medmouine-beneva yes! `@commitlint/cli` will also take the `commitlint.config.js` of your repo when running checks. If your repo doesn't have a `commitlint.config.js` file, you will need to create one with the following config:
```js
module.exports = { extends: ['@commitlint/config-conventional'] }
```

That's because this action uses this config by default if you repo doesn't have any commitlint config file 👍

**Comment by wagoid** [comment]
@medmouine-beneva ideally it would be better to have the commitlint dependencies in `devDependencies` of your `package.json` instead, so that all developers don't need to install it globally and you're sure everyone runs the same version.
Regarding `commitlint.config.js`, you can add to the same folder that your `package.json` is, `@commitlint/cli` will find it automatically 🚀 
A PR with docs would definitely be appreciated! ✍️ ❤️
