### ISSUE TITLE
Commitlint fails on `chore(release):` commits

### ISSUE THREAD

**Issue by StevenLangbroek** [wagoid/commitlint-github-action#61]
Heya! We're using commit-lint v2, and are running into a curious issue. The release commit as generated by semantic-release is rejected by commitlint.

For example, this commit message:

```md
# [2.9.0](v2.8.0...v2.9.0) (2020-11-19)

### Bug Fixes

* [redacted] ([#335](#335)) ([9939b0d](9939b0d))
* [redacted] ([b258d0a](b258d0a))
* fix unit tests and stop ignoring unit tests errors on CI ([39b931c](39b931c))

### Features

* [redacted] ([f4a779f](f4a779f))
* [redacted] ([2ed702f](2ed702f))
```

Fails with this error:

```
footer's lines must not be longer than 100 characters [footer-max-line-length]
```

What puzzles me is why commitlint thinks this is the footer, not the body. Any idea?

**Comment by wagoid** [comment]
hey @StevenLangbroek! That depends a bit on your commitlint config file. Could you show me your config file and the full error output?

**Comment by jdbruijn** [comment]
@StevenLangbroek That would be an issue with the commitlint config rather than with this action. [`@commitlint/config-conventional`](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) doesn't follow [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) exactly. The Conventional Commits standard doesn't specify anything about the length of a message and of each line length in the body and footer. I was running into similar issues with commits and have created my own configuration, [`@vidavidorra/commitlint-config`](https://github.com/vidavidorra/commitlint-config) that removes the line length limitation and allows longer commits specifically for tools like [Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate) and [Dependabot](https://dependabot.com/).

So IMHO you're best option is to manually change the configuration to disable rules for body/footer line length in your commitlint config or use my config and get the longer commit message for dependency tools additionally.

> What puzzles me is why commitlint thinks this is the footer, not the body. Any idea?

This is because empty lines in the commit message. See below the broken down commit to its parts. I suspect there was a line before that message with something like `chore(release): 2.9.0 [skip ci]`, in which case that would be the header and the header, body would shift and the body of the broken down message would be part of the footer.

```js
{
  type: null,
  scope: null,
  subject: null,
  merge: null,
  header: '# [2.9.0](v2.8.0...v2.9.0) (2020-11-19)',
  body: '### Bug Fixes',
  footer: '* [redacted] ([#335](#335)) ([9939b0d](9939b0d))\n' +
    '* [redacted] ([b258d0a](b258d0a))\n' +
    '* fix unit tests and stop ignoring unit tests errors on CI ([39b931c](39b931c))\n' +
    '\n' +
    '### Features\n' +
    '\n' +
    '* [redacted] ([f4a779f](f4a779f))\n' +
    '* [redacted] ([2ed702f](2ed702f))',
  notes: [],
  references: [
    {
      action: null,
      owner: null,
      repository: null,
      issue: '335',
      raw: '* [redacted] ([#335',
      prefix: '#'
    },
    {
      action: null,
      owner: null,
      repository: null,
      issue: '335',
      raw: '](#335',
      prefix: '#'
    }
  ],
  mentions: [],
  revert: null,
  raw: '# [2.9.0](v2.8.0...v2.9.0) (2020-11-19)\n' +
    '\n' +
    '### Bug Fixes\n' +
    '\n' +
    '* [redacted] ([#335](#335)) ([9939b0d](9939b0d))\n' +
    '* [redacted] ([b258d0a](b258d0a))\n' +
    '* fix unit tests and stop ignoring unit tests errors on CI ([39b931c](39b931c))\n' +
    '\n' +
    '### Features\n' +
    '\n' +
    '* [redacted] ([f4a779f](f4a779f))\n' +
    '* [redacted] ([2ed702f](2ed702f))\n'
}
```

**Comment by jdbruijn** [comment]
Hi @StevenLangbroek,

I'm closing this issue as this isn't an issue with this project but with the commitlint configuration. Please check my previous comment explaining your options. Feel free to reach out if you need help with your configuration.
